import axios from "axios";
export const getPlannerData = async () => {
  console.log("Hello from GeminiController");
  try {
    const res = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${
        import.meta.env.VITE_API_KEY
      }`,
      {
        contents: [
          {
            parts: [
              {
                text: `
I am working on a stress-management day-planner app that uses generative AI to help university students. Upon opening the app, the app will ask what tasks are stressing the person out. The task will be in this format:

1) Task name
2) Task priority
3) Is it a long term or short term task
4) Stress level (1 - 5) the task causes

Users can add multiple tasks. Then the app will ask for activities that help the user de-stress.
All of these responses will be fed to a generative AI. The AI will come up with a day-plan that the user can follow.
The response will contain the planner in a JSON format like this:
THE OBJECT SHOULD BE CALLED dailyPlan
{
    {
        "activityName": "",
        "startTime": ...,
        "endTime": ...
    },
    {
        "activityName": "",
        "startTime": ...,
        "endTime": ...
    }
}
If something is a long-term task, the response will contain a planner that has that task for about 20-30 minutes a day.
Throughout the day, the user can cross off tasks as "done". Or if they're feeling really stressed, they can let the app know, and it can re-structure the day-plan so that they can de-stress with a de-stress activity before they continue working. The re-structured day-plan will also be generated by AI.
You are the AI that will help with the day-planning. You will be given to-do tasks in this format:
Tasks:
1) Activity Name
2) Priority Level (1 - 5)
3) Long/short term task
4) If it is a short term task, you will be given a due date. If it is a long term task, you will be given an expected date

Then, you will be given the hobbies in this format:
Hobbies:
1) Hobby name
You should also make sure that the hobbies aren't harmful (like smoking, drinking etc) You can provide alternate activities based on other non-harmful activities provided.

IMPORTANT: Your responses should ONLY contain JSON objects. DO NOT INCLUDE ANY OTHER TEXT IN YOUR RESPONSE.

Here's a sample response you might get:

Tasks:
Task 1:
1) Assignment 2 English 101
2) 3
3) Short term
4) 3PM tomorrow

Task 2:
1) Test 3 Health 303
2) 4
3) Short term
4) 5PM tomorrow

Task 3:
1) Learn Python
2) 2
3) Long term
4) 1 year

Hobbies:

1) Playing the keyboard
2) Reading books
3) Playing soccer
`,
              },
            ],
          },
        ],
      }
    );
    const raw_response = res.data.candidates[0].content.parts[0].text;
    const cleaned_response = raw_response
      .replace("```json", "")
      .replace("```", "")
      .trim();
    const result = JSON.parse(cleaned_response);
    return result;
  } catch (error) {
    console.error(error);
  }
};
